columns:
  average_cost_for_two: float64
  city: object
  cuisine1: object
  cuisine2: object
  cuisine3: object
  cuisine4: object
  currency: object
  floor: object
  has_online_delivery: object
  has_table_booking: object
  is_delivering_now: object
  latitude: float64
  longitude: float64
  mall_name: object
  price_level: category
  price_range: int64
  rating_color: object
  rating_text: object
  street_name: object
  votes: float64
missing_values:
  average_cost_for_two: 0
  city: 1898
  cuisine1: 0
  cuisine2: 3049
  cuisine3: 6158
  cuisine4: 7822
  currency: 0
  floor: 0
  has_online_delivery: 0
  has_table_booking: 0
  is_delivering_now: 0
  latitude: 0
  longitude: 0
  mall_name: 18
  price_level: 236
  price_range: 0
  rating_color: 0
  rating_text: 0
  street_name: 275
  votes: 0
